version: '2'
services:
  mongodb:
    image: mongo:4.2.3-bionic
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  node:
    image: node:13.8.0-stretch
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "8082:80"
    volumes:
      - ./backend:/application
  react:
    image: node:13.8.0-stretch
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "8083:3000"
    volumes:
      - ./frontend/react:/application
  vue:
    image: node:13.8.0-stretch
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "8084:8084"
    volumes:
      - ./frontend/vue:/application
    environment:
      HOST: 0.0.0.0
  angular:
    image: node:13.8.0-stretch
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/angular:/application